@id = 60793f6478aa7a27b84e24e1

GET http://localhost:5000/api/wilders HTTP/1.1

###

GET http://localhost:5000/api/wilders/{{id}} HTTP/1.1

###

POST http://localhost:5000/api/wilders/ HTTP/1.1
Content-Type: application/json

{
  "name": "Paul",
  "city": "Orléans",
  "skills": [
    {"title": "express", "votes":7 },
    {"title": "mongo", "votes":2 }
  ]
}

###

PUT http://localhost:5000/api/wilders/{{id}} HTTP/1.1
Content-Type: application/json

{
  "name": "Levend"
}

###

DELETE http://localhost:5000/api/wilders/{{id}} HTTP/1.1

###

DELETE http://localhost:5000/api/wilders HTTP/1.1
