@id = 6076d983b83a7e433436d867

GET http://localhost:3000/api/wilders HTTP/1.1

###

GET http://localhost:3000/api/wilders/{{id}} HTTP/1.1

###

POST http://localhost:3000/api/wilders/ HTTP/1.1
Content-Type: application/json

{
  "name": "Wilder1",
  "city": "Paris",
  "skills": [
    {"title": "express", "votes":5 },
    {"title": "mongo", "votes":12 }
  ]
}

###

PUT http://localhost:3000/api/wilders/{{id}} HTTP/1.1
Content-Type: application/json

{
  "name": "Michel"
}

###

DELETE http://localhost:3000/api/wilders/{{id}} HTTP/1.1

###

DELETE http://localhost:3000/api/wilders HTTP/1.1
